service: linko-prueba-tecnica
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: handler.handler
    environment:
      SECRET_JWT_SEED: 3l0l1mp83L7rAn
      SECRET_JWT_EXPIRES: 24h
    events:
      - httpApi: '*'
